### ISSUE TITLE
Need moves implemented

### ISSUE THREAD

**Issue by TimothyZink** [TheGameDevGroup/MiniGames#10]
### Is your feature request related to a problem? Please describe

The Connect4 game does not have its PlaceMove method implemented (see Game.PlaceMove).

### Describe the solution you'd like

Should assume the move is valid (already checked).
Find the bottommost position in the specified column that does not already have a piece and set it using the player token provided.

### Describe alternatives you've considered

None

**Comment by acarston** [comment]
The GameState class already has this implemented. I will add the functionality to the PlaceMove method.

**Comment by TimothyZink** [comment]
Complete as of #17
