### ISSUE TITLE
Merge Game and GameState classes

### ISSUE THREAD

**Issue by acarston** [TheGameDevGroup/MiniGames#16]
### Affected Project

Connect4

### What is currently being done?

Nothing yet.

### Why should this change?

The Game and GameState classes are not well defined. Functionality is mixed between Game and GameState, quite arbitrarily.

### How can this be improved?

 I propose that all backend logic be merged into GameState. Game will then handle events , such as the PlaceMove method.

### Why should the proposed way be used instead?

For the sake of organization.

### What are potential issues with the proposed improvements?

Game might become sparse.

**Comment by TimothyZink** [comment]
Could I propose an alternative? Merge everything into Game instead of GameState. The "state" of the game is really just an array; having an entire class for it is unnecessary.

**Comment by TimothyZink** [comment]
Closed as of #17
