### ISSUE TITLE
Add middle click functionality and flags

### ISSUE THREAD

**Issue by ElijahWurst** [TheGameDevGroup/MiniGames#46]
### Affected Project

Minesweeper

### Is your feature request related to a problem? Please describe

right now, the middle click does the same thing as the left and right click.

### Describe the solution you'd like

When middle-clicking on a number with the correct amount of flags adjacent to it, all the adjacent unflagged tiles should be opened.

### Describe alternatives you've considered

no

### Additional context

no

**Comment by TimothyZink** [comment]
Added in #54
