### ISSUE TITLE
Need to check for winning player

### ISSUE THREAD

**Issue by TimothyZink** [TheGameDevGroup/MiniGames#9]
### Is your feature request related to a problem? Please describe

Currently the method to check if a player has won is unimplemented (see Game.PlayerWon).

### Describe the solution you'd like

The function needs to be finished so that it returns true when the specified player has won.

This could be accomplished by iterating through each position in the game state, looking for one of the player's tokens. When it finds one, search around it to check for other pieces belonging to the player. Then, continue checking in a line to see if there are four in a row.

### Describe alternatives you've considered

There are probably much better ways of doing this, suggestions?

### Additional context

Possible optimization:
- Start the search at the top
- When a piece is found, only check the pieces below it (the pieces above were already checked).
- Do not need to go all the way to the bottom (need four in a row; if the starting piece is less than four away from an edge, it is impossible to have four in a row in that direction).
- See the diagram below; starting at the piece in the top left, only the bold pieces need to be checked:
**o o o o**
**o o** o o
**o** o **o** o
**o** o o **o**

**Comment by acarston** [comment]
Currently working on this; will give implementation updates.

**Comment by acarston** [comment]
Suggestion: only make checks around the most recently placed piece. If there are pieces of the same playerToken in immediate proximity, check for connect-4s in those directions.

**Comment by acarston** [comment]
Update: feature successfully implemented using 8 recursive functions. It may be possible to abstract them into 1. The code may be optimized not to use recursion.

**Comment by acarston** [comment]
Update: realized that 3 of the 8 functions are completely pointless due to the nature of the game. We never need to check for a connect 4 above the current piece because gravity dictates that there will never be a piece there.

**Comment by acarston** [comment]
Update: I revoke the last comment. Only checking directly above is redundant. The other 7 directions are necessary

**Comment by acarston** [comment]
Update: Condensed all 7 functions into 1. Removed recursion. Testing has proven successful.

**Comment by TimothyZink** [comment]
Changes from #15 were brought over to #17. This can now be closed as #17 has been merged.
